openapi: 3.0.0
info:
  title: Notification Service API
  description: API for managing notifications in the online order processing system
  version: 1.0.0
servers:
  - url: http://localhost:8085
    description: Local development server
paths:
  /notifications:
    get:
      summary: Get all notifications
      description: Returns a list of all notifications
      parameters:
        - name: recipient
          in: query
          description: Filter notifications by recipient
          required: false
          schema:
            type: string
        - name: type
          in: query
          description: Filter notifications by type
          required: false
          schema:
            type: string
            enum: [ORDER_CONFIRMATION, ORDER_STATUS_UPDATE, SHIPMENT_UPDATE, PAYMENT_CONFIRMATION, LOW_INVENTORY]
        - name: status
          in: query
          description: Filter notifications by status
          required: false
          schema:
            type: string
            enum: [PENDING, SENT, FAILED]
      responses:
        '200':
          description: A list of notifications
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Notification'
    post:
      summary: Send a new notification
      description: Sends a new notification with the provided information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotificationRequest'
      responses:
        '201':
          description: Notification sent successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notification'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /notifications/{id}:
    get:
      summary: Get notification by ID
      description: Returns a single notification by ID
      parameters:
        - name: id
          in: path
          description: Notification ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Notification found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notification'
        '404':
          description: Notification not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    NotificationRequest:
      type: object
      properties:
        type:
          type: string
          enum: [ORDER_CONFIRMATION, ORDER_STATUS_UPDATE, SHIPMENT_UPDATE, PAYMENT_CONFIRMATION, LOW_INVENTORY]
          description: Type of notification
        recipient:
          type: string
          description: Recipient of the notification (email, phone number, etc.)
        channel:
          type: string
          enum: [EMAIL, SMS, PUSH]
          description: Channel to send the notification through
        subject:
          type: string
          description: Subject of the notification
        content:
          type: string
          description: Content of the notification
        data:
          type: object
          description: Additional data for the notification
      required:
        - type
        - recipient
    Notification:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the notification
        type:
          type: string
          enum: [ORDER_CONFIRMATION, ORDER_STATUS_UPDATE, SHIPMENT_UPDATE, PAYMENT_CONFIRMATION, LOW_INVENTORY]
          description: Type of notification
        recipient:
          type: string
          description: Recipient of the notification (email, phone number, etc.)
        channel:
          type: string
          enum: [EMAIL, SMS, PUSH]
          description: Channel the notification was sent through
        subject:
          type: string
          description: Subject of the notification
        content:
          type: string
          description: Content of the notification
        status:
          type: string
          enum: [PENDING, SENT, FAILED]
          description: Current status of the notification
        data:
          type: object
          description: Additional data for the notification
        created_at:
          type: string
          format: date-time
          description: Time when the notification was created
        sent_at:
          type: string
          format: date-time
          description: Time when the notification was sent
    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
