openapi: 3.0.0
info:
  title: Payment Service API
  description: API for managing payments in the online order processing system
  version: 1.0.0
servers:
  - url: http://localhost:8083
    description: Local development server
paths:
  /payments:
    get:
      summary: Get all payments
      description: Returns a list of all payments
      parameters:
        - name: order_id
          in: query
          description: Filter payments by order ID
          required: false
          schema:
            type: string
        - name: status
          in: query
          description: Filter payments by status
          required: false
          schema:
            type: string
            enum: [PENDING, SUCCESSFUL, FAILED]
      responses:
        '200':
          description: A list of payments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Payment'
    post:
      summary: Create a new payment
      description: Creates a new payment with the provided information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePaymentRequest'
      responses:
        '201':
          description: Payment created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payment'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /payments/{id}:
    get:
      summary: Get payment by ID
      description: Returns a single payment by ID
      parameters:
        - name: id
          in: path
          description: Payment ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Payment found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payment'
        '404':
          description: Payment not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /payments/{id}/status:
    put:
      summary: Update payment status
      description: Updates the status of a payment
      parameters:
        - name: id
          in: path
          description: Payment ID
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum: [PENDING, SUCCESSFUL, FAILED]
              required:
                - status
      responses:
        '200':
          description: Payment status updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payment'
        '404':
          description: Payment not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    CreatePaymentRequest:
      type: object
      properties:
        order_id:
          type: string
          description: ID of the order to be paid
        amount:
          type: number
          format: float
          description: Amount to be paid
        payment_method:
          type: string
          enum: [credit_card, debit_card, paypal, bank_transfer, card]
          description: Payment method
        card_number:
          type: string
          description: Credit/debit card number (if applicable)
        expiry_month:
          type: string
          description: Card expiry month (if applicable)
        expiry_year:
          type: string
          description: Card expiry year (if applicable)
        cvv:
          type: string
          description: Card CVV (if applicable)
      required:
        - order_id
        - amount
        - payment_method
    Payment:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the payment
        order_id:
          type: string
          description: ID of the order being paid
        amount:
          type: number
          format: float
          description: Amount paid
        status:
          type: string
          enum: [PENDING, SUCCESSFUL, FAILED]
          description: Current status of the payment
        payment_method:
          type: string
          enum: [credit_card, debit_card, paypal, bank_transfer, card]
          description: Payment method used
        transaction_id:
          type: string
          description: Transaction ID from the payment processor
        created_at:
          type: string
          format: date-time
          description: Time when the payment was created
    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
